---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ghcr.io/ivanovac/cfbuildpacks/ci
    USERNAME: $USERNAME
    PASSWORD: $GITHUBPAT
inputs:
  - name: buildpacks-ci
  - name: verification-whitelist
  - name: nodejs-buildpack
  - name: ruby-buildpack
  - name: go-buildpack
  - name: python-buildpack
  - name: staticfile-buildpack
  - name: binary-buildpack
  - name: php-buildpack
  - name: dotnet-core-buildpack
  - name: hwc-buildpack
params:
  USERNAME: ((coredeps-dockerhub-user.username))
  PASSWORD: ((coredeps-dockerhub-user.password))
outputs:
  - name: buildpack-artifacts
run:
  # path: buildpacks-ci/tasks/verify-buildpack-binaries/run.rb  
  path: bash
  args:
    - -c
    - |
      set -euo pipefail
      echo "Environment Variables:"
      env
      echo "Hostname: $HOSTNAME"
      echo "Current os-release:"
      cat /etc/os-release
      buildpacks-ci/tasks/verify-buildpack-binaries/run.rb
