---
platform: linux
params:
  USERNAME: ((coredeps-dockerhub-user.username))
  PASSWORD: ((coredeps-dockerhub-user.password))
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci
    USERNAME: $USERNAME
    PASSWORD: $PASSWORD
inputs:
  - name: buildpacks-ci
  - name: verification-whitelist
  - name: nodejs-buildpack
  - name: ruby-buildpack
  - name: go-buildpack
  - name: python-buildpack
  - name: staticfile-buildpack
  - name: binary-buildpack
  - name: php-buildpack
  - name: dotnet-core-buildpack
  - name: hwc-buildpack
outputs:
  - name: buildpack-artifacts
run:
  path: buildpacks-ci/tasks/verify-buildpack-binaries/run.rb
